apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "technical-tests"
  namespace: "technical-test"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "technical-tests"
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50