apiVersion: v1
kind: Service
metadata:
  name: "anz-technical-zeyu"
  namespace: "technical-test"
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  type: NodePort
  selector:
    app: "anz-technical-zeyu"